<?php
/**
 * @copyright Copyright © 2014 Rollun LC (http://rollun.com/)
 * @license LICENSE.md New BSD License
 */

namespace rollun\test\old\DataStore\Factory;

use PHPUnit\Framework\TestCase;
use Zend\ServiceManager\Factory\AbstractFactoryInterface;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-29 at 18:23:51.
 */
class MemoryAbstractFactoryTest extends TestCase
{
    /**
     * @var AbstractFactoryInterface
     */
    protected $object;

    public function testDataStoreMemory__invoke()
    {
        $container = include 'config/container.php';
        $this->object = $container->get('testMemory');
        $this->assertSame(
                get_class($returnedResponse = $this->object), 'rollun\datastore\DataStore\Memory'
        );
    }
}
