<?php $this->headTitle('Warning item'); ?>

<div class="row">
    <div class="col-md-4">
        <h2>Load conformity table</h2>
        <form enctype="multipart/form-data" action="<?php echo $this->url('upload-service') ?>" method="POST">
            Отправить этот файл: <input name="userfile" type="file" />
            <input type="submit" value="Send File" />
        </form>
    </div>
    <div class="col-md-8">
        <h2>Warning Items</h2>
        <table>
            <tr>
                <td>sku </td>
                <td>mpn </td>
                <td>asin </td>
                <td>QTY_UT </td>
                <td>QTY_KY</td>
            </tr>
            <?php if (is_array($this->data)) : ?>
                <?php foreach ($this->data as $item) : ?>
                    <tr>
                        <td><?php echo $item['sku'] ?></td>
                        <td><?php echo $item['mpn'] ?></td>
                        <td><?php echo $item['asin'] ?></td>
                        <td><?php echo $item['QTY_UT'] ?></td>
                        <td><?php echo $item['QTY_KY'] ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
        </table>
    </div>
</div>
