<?php

namespace rollun\datastore\rest\Middleware;

use rollun\datastore\DataStore\Memory;
use rollun\datastore\Examples\Middleware\DataStoreMemory;
use Zend\Diactoros\Response;
use Zend\Diactoros\ServerRequest;
use Zend\Stratigility\Delegate\CallableDelegateDecorator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-29 at 18:23:51.
 */
class DataStoreMemoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Returner
     */
    protected $object;


    /*
     * @var Zend\Diactoros\ServerRequest;
     */
    protected $request;

    /*
     * @var \Callable
     */
    protected $delegator;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DataStoreMemory();
        $response = new Response();
        $this->request = new ServerRequest([], [], '/foo');
        $this->delegator = new CallableDelegateDecorator(function ($req, $resp) {
            return $req;
        }, $response);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function testDataStoreMemory__invoke()
    {
        $returnedResponse = $this->object
                ->process($this->request, $this->delegator);
        $this->assertSame(
                get_class($returnedResponse->getAttribute('memoryStore')), Memory::class
        );
    }

}
