<?php

namespace rollun\test\datastore\Middleware;

use rollun\datastore\Middleware\ResourceResolver;
use Zend\Diactoros\Response;
use Zend\Diactoros\ServerRequest;
use rollun\datastore\DataStore\Memory;
use Zend\Stratigility\Delegate\CallableDelegateDecorator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-29 at 18:23:51.
 */
class ResourceResolverTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ResourceResolver
     */
    protected $object;
    
    /*
     * @var Zend\Diactoros\Response
     */
    protected $response;
    
    /*
     * @var Zend\Diactoros\ServerRequest;
     */
    protected $request;
    
    /*
     * @var \Callable
     */
    protected $next;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ResourceResolver();
        $this->response = new Response();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testResourceResolver__invokeResourceName1() {
        $this->request = new ServerRequest([], [], '/foo');
        $this->next = function ($req, $resp) {
            return $req;
        };
        $returnedResponse = $this->object
                ->process($this->request, new CallableDelegateDecorator($this->next, $this->response));
        $this->assertSame(
                $returnedResponse->getAttribute('resourceName'),
                'foo'
        );
        $this->assertSame(
                $returnedResponse->getAttribute('primaryKeyValue'),
                null
        );  
    }

    public function testResourceResolver__invokeResourceName2() {
        $this->request = new ServerRequest([], [], '/foo-bar_baz/2');
        $this->next = function ($req, $resp) {
            return $req;
        };
        $returnedResponse = $this->object
            ->process($this->request, new CallableDelegateDecorator($this->next, $this->response));
        $this->assertSame(
                $returnedResponse->getAttribute('resourceName'),
                'foo-bar_baz'
        );
        $this->assertSame(
                $returnedResponse->getAttribute('primaryKeyValue'),
                '2'
        );  
    }
    

    public function testResourceResolver__invokeResourceName3() {
        $this->request = new ServerRequest([], [], '/1foo-AbarD_baz3/a-b_C2?A=2&bd=cd');
        $this->next = function ($req, $resp) {
            return $req;
        };
        $returnedResponse = $this->object
            ->process($this->request, new CallableDelegateDecorator($this->next, $this->response));
        $this->assertSame(
                $returnedResponse->getAttribute('resourceName'),
                '1foo-AbarD_baz3'
        );
        $this->assertSame(
                $returnedResponse->getAttribute('primaryKeyValue'),
                'a-b_C2'
        );  
    }

    public function testResourceResolver__invokeResourceName4() {
        $this->request = new ServerRequest([], [], '/123?A=2&bd=cd');
        $this->next = function ($req, $resp) {
            return $req;
        };
        $returnedResponse = $this->object
            ->process($this->request, new CallableDelegateDecorator($this->next, $this->response));
        $this->assertSame(
                $returnedResponse->getAttribute('resourceName'),
                '123'
        );
        $this->assertSame(
                $returnedResponse->getAttribute('primaryKeyValue'),
                null
        );  
    }

    public function testResourceResolver__invokeResourceName5() {
        $this->request = new ServerRequest([], [], '/');
        $this->next = function ($req, $resp) {
            return $req;
        };
        $returnedResponse = $this->object
            ->process($this->request, new CallableDelegateDecorator($this->next, $this->response));
        $this->assertSame(
                $returnedResponse->getAttribute('resourceName'),
                null
        );
        $this->assertSame(
                $returnedResponse->getAttribute('primaryKeyValue'),
                null
        );  
    }
    
}
