<?php

/**
 * Zaboy lib (http://zaboy.org/lib/)
 *
 * @copyright  Zaboychenko Andrey
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 */

namespace rollun\test\datastore\DataStore\Eav;

use rollun\datastore\DataStore\Eav\SysEntities;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-11 at 16:19:25.
 */
class EntityTest extends EntityTestAbstract
{

    protected function __init()
    {
        $this->object = $this->container->get(SysEntities::ENTITY_PREFIX . 'product');
    }

    public function test__getEntityName()
    {
        $this->__init();
        $this->assertEquals('product', $this->object->getEntityName());
    }
}
