name: PHP Composer

on:
  push:
    branches: [ master, fix/ci-tests ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      # https://github.com/docker/compose/issues/7306
      COMPOSE_INTERACTIVE_NO_CLI: 1
    steps:
      - uses: actions/checkout@v2

      - name: Docker compose up
        run: docker compose up -d

      - name: Composer install
        run: docker compose exec -T rollun-datastore-php-fpm composer install

      - name: Wait db to be ready
        run: docker compose exec rollun-datastore-php-fpm wait-for-it rollun-datastore-mysql:3306 -t 30

      - name: Run tests
        run: docker compose exec -T rollun-datastore-php-fpm composer test